### PR TITLE
added range ports

### PR DESCRIPTION
**Pull request by AlbertoFemenias**
Following issue #147:
Now you can "range" ports if you want to define a very big list of open ports in a container or service (open a lot of contiguous ports). Just add "range" to your port definition.

If you want to range service ports and match them all to the same pod port, use the "range_service" key instead.

### values.yaml
```yaml
#values.yaml
selector:
  app: wordpress

image:  wordpress:latest

ports:
  - service: 80
    pod: 80
  - service: 40005
    pod: 40005
    protocol: UDP
    range: 3
  - service: 10000
    pod: 10000
    protocol: UDP
    range_service: 3
```

### deployment.yaml
```yaml
{{ define "wordpress.data"  }}
name: deployment-{{ .Release.Name }}-wordpress
selector:  {{ .Values.selector | toYaml | nindent 2}}
replicas: 1

serviceAccountName: {{ .Release.Name }}-svc-account
containers:
- name: {{ .Chart.Name }}
  image: {{ .Values.image }}
  ports: {{ .Values.ports | toYaml | nindent 6 }}

{{- end }}

 
{{ include "ph.deployment.render" (include "wordpress.data" . | fromYaml )  }}
 
```

```yaml
#service.yaml
{{ define "wordpress.service.data"  }}
name: {{ .Release.Name }}-service
selector:  {{ .Values.selector | toYaml | nindent 2}}
ports: {{ .Values.ports | toYaml | nindent 6 }}

{{- end }}
{{ include "ph.service.render" (include "wordpress.service.data" . | fromYaml )  }}
```
### Output
Those three files will produce the following resources:
```yaml
# helm template output
---
# Source: wordpress/templates/service.yaml
apiVersion: v1
kind: Service

metadata:
  name: RELEASE-NAME-service
spec:
  selector: 
    app: wordpress
  type: ClusterIP
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
      
  - protocol: UDP
    targetPort: 40005
    port: 40005
      
  - protocol: UDP
    targetPort: 40006
    port: 40006
      
  - protocol: UDP
    targetPort: 40007
    port: 40007
      
  - protocol: UDP
    targetPort: 10000
    port: 10000
      
  - protocol: UDP
    targetPort: 10000
    port: 10001
      
  - protocol: UDP
    targetPort: 10000
    port: 10002

---
# Source: wordpress/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1

metadata:
  name: deployment-RELEASE-NAME-wordpress

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata:
      labels: 
        app: wordpress
      annotations:
    spec: 
      containers: 
          - name: wordpress
            image: "wordpress:latest"
            imagePullPolicy: IfNotPresent
            env: 
            envFrom: 
            ports: 
            
            - containerPort: 80
              protocol: TCP
              
            - containerPort: 40005
              protocol: UDP
                
            - containerPort: 40006
              protocol: UDP
                
            - containerPort: 40007
              protocol: UDP
                
            volumeMounts: 
            resources: 
              requests: 
                  {}
              limits: 
                  {} 
      serviceAccountName: RELEASE-NAME-svc-account
      imagePullSecrets: 
      volumes:

### CODE REVIEW

**Review by alexandrenegreira — COMMENTED** [review]
There's any way not to add ports to service when use multiple and only add to container?

Like only use port.pod and port.protocol and not to use port.service

**Comment by AlbertoFemenias** [comment]
> There's any way not to add ports to service when use multiple and only add to container?
> 
> Like only use port.pod and port.protocol and not to use port.service

@alexandrenegreira  I kept both service port and pod port so you can do something like this:

values.yaml
```
...
- service: 31001
    pod: 54020
    protocol: UDP
    multiply: 3
```

output:
```

...
- protocol: UDP
    targetPort: 31001
    port: 54020
      
  - protocol: UDP
    targetPort: 31002
    port: 54021
      
  - protocol: UDP
    targetPort: 31003
    port: 54022
```

**Comment by frmadem** [comment]
@AlbertoFemenias could we change the multiply for the following sentence:

```yaml
---
...
- service: 31001
   pod: 54020
   protocol: UDP
   range-service: 3  # only increases service ports

- service: 31001
   pod: 54020
   protocol: UDP
   range: 5   # increases both service and pod ports
```

**Review by frmadem — APPROVED** [review]
LGTM!

**Pull request merged**
